/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'light-primary': '#ffffff',
        'light-secondary': '#fef2f2',
        'light-card': '#ffffff',
        'light-bg': '#fef2f2',
        'light-border': '#fecaca',
        'pure-white': '#ffffff',
        'light-glass': 'rgba(255, 255, 255, 0.9)',
        'light-glass-red': 'rgba(239, 68, 68, 0.1)',
        'accent-red': '#ef4444',
        'accent-red-dark': '#dc2626',
        'accent-red-light': '#f87171',
        'primary-red': '#ef4444',
        'secondary-red': '#dc2626',
        'dark-red': '#b91c1c',
        'light-red': '#fca5a5',
        'pale-red': '#fee2e2',
        'deep-red': '#991b1b',
        'medium-red': '#ef4444',
        'bright-red': '#f87171',
        'text-dark': '#111827',
        'text-gray': '#4b5563',
        'text-light': '#6b7280',
        'pale-yellow': '#fef3c7',
        'label-red': '#ef4444',
        'trust-red': '#dc2626',
        'success-red': '#f87171',
        'neon-red': '#f87171',
        'soft-red': '#fca5a5',
        'rose-red': '#fb7185',
        mizuho: {
          blue: '#003087',
          'blue-light': '#0055B8',
          'blue-dark': '#002266',
          cyan: '#00A3AF',
          'cyan-light': '#00C4D0',
          'cyan-dark': '#008A94',
          orange: '#FF6B35',
          'orange-light': '#FF8A5C',
          'orange-dark': '#E85A2A',
          purple: '#6B4C9A',
          'purple-light': '#8B6CB8',
          'purple-dark': '#4B2C7A',
          gray: '#F5F5F5',
          'gray-light': '#FAFAFA',
          'gray-dark': '#E0E0E0',
        },
      },
      backgroundImage: {
        'light-gradient': 'linear-gradient(to bottom right, #ffffff, #fef2f2, #ffffff)',
        'light-tech-gradient': 'linear-gradient(to bottom, #ffffff, #fef2f2, #ffffff)',
        'red-glow': 'radial-gradient(circle, rgba(239, 68, 68, 0.2), transparent)',
        'red-glow-soft': 'radial-gradient(circle, rgba(239, 68, 68, 0.15), transparent)',
        'red-glow-strong': 'radial-gradient(circle, rgba(220, 38, 38, 0.3), transparent)',
        'white-to-red': 'linear-gradient(to bottom, #ffffff, #fef2f2)',
        'red-horizontal': 'linear-gradient(to right, #b91c1c, #ef4444)',
        'red-radial': 'radial-gradient(circle, #ef4444, transparent)',
        'tech-gradient': 'linear-gradient(135deg, #ffffff 0%, #fef2f2 50%, #ffffff 100%)',
        'red-gradient': 'linear-gradient(to right, #ef4444, #f87171)',
        'rose-gradient': 'linear-gradient(to right, #dc2626, #f87171)',
        'mizuho-gradient': 'linear-gradient(135deg, #003087 0%, #0055B8 100%)',
        'mizuho-gradient-vertical': 'linear-gradient(to bottom, #003087 0%, #0055B8 100%)',
        'cyan-gradient': 'linear-gradient(135deg, #00A3AF 0%, #00C4D0 100%)',
        'orange-gradient': 'linear-gradient(135deg, #FF6B35 0%, #FF8A5C 100%)',
        'wave-pattern': "url('/images/mizuho/wave-pattern.svg')",
      },
      boxShadow: {
        'red-glow': '0 0 20px rgba(239, 68, 68, 0.5)',
        'red-glow-lg': '0 0 40px rgba(239, 68, 68, 0.6)',
        'yellow-glow': '0 0 15px rgba(254, 249, 195, 0.6)',
        'red-soft': '0 0 25px rgba(239, 68, 68, 0.4)',
        'red-soft-lg': '0 0 45px rgba(239, 68, 68, 0.6)',
        'rose-glow': '0 0 25px rgba(251, 113, 133, 0.4)',
        'rose-glow-lg': '0 0 45px rgba(251, 113, 133, 0.6)',
        'light-glow': '0 0 20px rgba(252, 165, 165, 0.5)',
        'tech-glow': '0 4px 20px rgba(239, 68, 68, 0.3)',
        'neon-red': '0 0 30px rgba(248, 113, 113, 0.6)',
        'soft-red-glow': '0 0 20px rgba(252, 165, 165, 0.5)',
        'card-shadow': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
      },
      animation: {
        'pulse-red': 'pulse-red 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-red-soft': 'pulse-red-soft 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 3s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite',
        'slide-up': 'slide-up 0.5s ease-out',
        'fade-in': 'fade-in 0.6s ease-out',
        'gradient-shift-slow': 'gradient-shift-slow 8s ease infinite',
        'pulse-slow': 'pulse-slow 6s ease-in-out infinite',
        'spin-slow': 'spin-slow 20s linear infinite',
        'radar-sweep': 'radar-sweep 4s linear infinite',
        'pulse-subtle': 'pulse-subtle 3s ease-in-out infinite',
        'scroll-step': 'scroll-step 20s linear infinite',
      },
      keyframes: {
        'pulse-red': {
          '0%, 100%': { opacity: 1, boxShadow: '0 0 20px rgba(239, 68, 68, 0.5)' },
          '50%': { opacity: 0.8, boxShadow: '0 0 40px rgba(239, 68, 68, 0.8)' },
        },
        'pulse-red-soft': {
          '0%, 100%': { opacity: 1, boxShadow: '0 0 25px rgba(239, 68, 68, 0.4)' },
          '50%': { opacity: 0.9, boxShadow: '0 0 45px rgba(239, 68, 68, 0.7)' },
        },
        'spin-slow': {
          'from': { transform: 'rotate(0deg)' },
          'to': { transform: 'rotate(360deg)' },
        },
        'radar-sweep': {
          'from': { transform: 'rotate(0deg)' },
          'to': { transform: 'rotate(360deg)' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'glow': {
          '0%, 100%': { opacity: 0.5 },
          '50%': { opacity: 1 },
        },
        'slide-up': {
          '0%': { transform: 'translateY(20px)', opacity: 0 },
          '100%': { transform: 'translateY(0)', opacity: 1 },
        },
        'fade-in': {
          '0%': { opacity: 0 },
          '100%': { opacity: 1 },
        },
        'gradient-shift-slow': {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        'pulse-slow': {
          '0%, 100%': { opacity: 0.3, transform: 'scale(1)' },
          '50%': { opacity: 0.5, transform: 'scale(1.1)' },
        },
        'pulse-subtle': {
          '0%, 100%': { opacity: 1 },
          '50%': { opacity: 0.9 },
        },
        'scroll-step': {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(-50%)' },
        },
      },
      fontFamily: {
        'sans': ['"Noto Sans JP"', '-apple-system', 'BlinkMacSystemFont', '"Helvetica Neue"', 'Arial', '"游ゴシック体"', '"Yu Gothic"', '"YuGothic"', '"ヒラギノ角ゴ ProN"', '"Hiragino Kaku Gothic ProN"', '"メイリオ"', '"Meiryo"', 'sans-serif'],
        'title': ['HYYaKuHeiW', '"Noto Sans JP"', 'sans-serif'],
        'subtitle': ['Adobe Heiti Std', 'Hiragino Sans', 'sans-serif'],
        'artistic': ['"Kosugi Maru"', '"M PLUS Rounded 1c"', '"RocknRoll One"', '"Zen Kaku Gothic New"', '"Noto Sans JP"', 'sans-serif'],
        'heading': ['"Kaisei Opti"', '"Zen Kaku Gothic New"', '"Noto Sans JP"', 'sans-serif'],
      },
      spacing: {
        '7.5': '30px',
        '18': '72px',
        '22': '88px',
        '26': '104px',
        '28': '112px',
        '30': '120px',
        '36': '144px',
        '40': '160px',
      },
    },
  },
  plugins: [],
};
